[package]
name = "dicer"
version = "0.1.0"
authors = ["mattcorbin <mcorbin93@gmail.com>"]
edition = "2018"
repository = "https://github.com/mattcorbin/diceman"
keywords = ["dice"]
license-file = "LICENSE"

[dependencies]
rand = "0.7"
actix-web = "3"
serde = "1"
serde_json = "1"