name: Rust

on:
  push:
    branches: [ master ]
    paths: dicer/
  pull_request:
    branches: [ master ]
    paths: dicer/

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run coverage
      run: cargo taurpaulin --verbose
